version: 2

services:
  openvpn:
    container_name: openvpn-privacy

    image: strootje/openvpn-client
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
    - '6789:6789/tcp' # nzbget
    - '9091:9091/tcp' # transmission
    - '51413:51413/tcp' # transmission
    - '51413:51413/udp' # transmission
    volumes:
    - '${OPENVPN_VOLUMES_DIR}/stunnel:/etc/stunnel:ro'
    - '${OPENVPN_VOLUMES_DIR}/vpn:/vpn:ro'
    devices:
    - '/dev/net/tun:/dev/net/tun'
    cap_add:
    - NET_ADMIN
    environment:
    - 'GROUPID=${PGID}'
    - 'TZ=${TZ}'
    - 'ROUTE=${ROUTE}'

  transmission:
    container_name: transmission

    depends_on:
    - openvpn

    image: linuxserver/transmission
    restart: unless-stopped
    network_mode: 'service:openvpn'
    volumes:
    - 'transmission-config:/config'
    - '${TRANSMISSION_VOLUMES_DIR}/downloads:/downloads'
    - '${TRANSMISSION_VOLUMES_DIR}/watch:/watch'
    environment:
    - 'PUID=${PUID}'
    - 'PGID=${PGID}'
    - 'TZ=${TZ}'

  nzbget:
    container_name: nzbget

    depends_on:
    - openvpn

    image: linuxserver/nzbget
    restart: unless-stopped
    network_mode: 'service:openvpn'
    volumes:
    - 'nzbget-config:/config'
    - '${NZBGET_VOLUMES_DIR}/downloads:/downloads'
    environment:
    - 'PUID=${PUID}'
    - 'PGID=${PGID}'
    - 'TZ=${TZ}'

volumes:
  transmission-config:
  nzbget-config:
