---
kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: install
  image: node:alpine
  commands:
  - npx pnpm i

- name: build
  image: node:alpine
  commands:
  - npx pnpm run build

# - name: deploy
#   image: node:alpine
#   commands:
#   - npx surge /drone/src/dist/ bottles.surge.sh
#   environment:
#     SURGE_LOGIN:
#       from_secret: SURGE_LOGIN
#     SURGE_TOKEN:
#       from_secret: SURGE_TOKEN
