---
kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: install
  image: node
  commands:
  - npx pnpm i

- name: build
  image: node
  commands:
  - npx pnpm run build:templates

- name: deploy
  image: node
  commands:
  - npx surge --token ${SURGE_TOKEN} /drone/src/dist/ bottles.surge.sh
