language: node_js
node_js: lts/*

services:
  - docker

cache:
  npm: true
  directories:
  - $HOME/.pnpm-store/

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

script:
- pnpm run build

deploy:
- provider: surge
  project: ./dist/
  domain: bottles.surge.sh
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: bash ./scripts/deploy/docker.sh
  on:
    branch: master
