version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
    - '${ACKEE_VOLUMES_DIR}/data:/data/db'
    environment:
    - 'PUID=${PUID}'
    - 'PGID=${PGID}'
    - 'TZ=${TZ}'

  ackee:
    container_name: ackee
    depends_on:
    - mongo
    image: electerious/ackee
    restart: unless-stopped
    ports:
    - '3030:3000'
    environment:
    - 'PUID=${PUID}'
    - 'PGID=${PGID}'
    - 'TZ=${TZ}'
    - 'VIRTUAL_HOST=${VIRTUAL_HOST}'
    - 'VIRTUAL_PORT=${VIRTUAL_PORT}'
    - 'LETSENCRYPT_HOST=${LETSENCRYPT_HOST}'
    - 'WAIT_HOSTS=mongo:27017'
    - 'ACKEE_USERNAME=${ACKEE_USERNAME}'
    - 'ACKEE_PASSWORD=${ACKEE_PASSWORD}'
    - 'ACKEE_MONGODB=mongodb://mongo:27017/ackee'
