version: '2'

volumes:
  config: ~

services:
  app:
    image: linuxserver/heimdall
    restart: unless-stopped
    volumes:
      - config:/config
    ports:
      - 3030:80
      - 3031:443
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
