version: "3.2"

networks:
  owncloud_db_net:
    driver: bridge

  owncloud_redis_net:
    driver: bridge

volumes:
  owncloud_dbdata: ~
  owncloud_redis: ~
  owncloud_files: ~

services:
  owncloud_db:
    image: postgres:9-alpine
    container_name: owncloud_db
    restart: unless-stopped
    networks:
      - owncloud_db_net
    volumes:
      - owncloud_dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=owncloud
      - POSTGRES_PASSWORD=owncloud

  owncloud_redis:
    image: redis:alpine
    container_name: owncloud_redis
    restart: unless-stopped
    networks:
      - owncloud_redis_net
    volumes:
      - owncloud_redis:/var/lib/redis
    environment:
      - REDIS_DATABASES=1

  owncloud_app:
    image: owncloud/server
    container_name: owncloud_app
    restart: unless-stopped
    depends_on:
      - owncloud_db
      - owncloud_redis
    networks:
      - owncloud_db_net
      - owncloud_redis_net
    volumes:
      - owncloud_files:/mnt/data
    ports:
      - 3020:8080
    environment:
      - OWNCLOUD_DOMAIN=0.0.0.0
      - OWNCLOUD_DB_TYPE=pgsql
      - OWNCLOUD_DB_HOST=owncloud_db
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=owncloud_redis
