version: '2'

services:
  nginx:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
    - '80:80/tcp'
    - '443:443/tcp'
    volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - '/etc/nginx/vhost.d'
    - '/usr/share/nginx/html'
    - '${NGINX_VOLUMES_DIR}/config/keys:/etc/nginx/certs'
    environment:
    - 'PUID=${PUID}'
    - 'PGID=${PGID}'
    - 'TZ=${TZ}'
    - 'DEFAULT_HOST=${DEFAULT_HOST}'

  letsencrypt:
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
    - nginx
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: unless-stopped
    network_mode: 'bridge'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
    - nginx
    environment:
    - 'PUID=${PUID}'
    - 'PGID=${PGID}'
    - 'TZ=${TZ}'
    - 'DEFAULT_EMAIL=${DEFAULT_EMAIL}'
