version: "3.2"

networks:
  redworld_net:
    driver: bridge

volumes:
  world_overworld: ~
  world_nether: ~
  world_the_end: ~

services:
  redworld_bungee:
    build:
      context: ./
      dockerfile: ./bungeecord.dockerfile
    networks:
      - redworld_net
    volumes:
      - ./configs/bungee.yml:/usr/src/server/config.yml:ro
    ports:
      - 25565:25565

  redworld_hubserver:
    build:
      context: ./
      dockerfile: ./hubserver.dockerfile
    networks:
      - redworld_net
    volumes:
      - ./configs/eula.txt:/usr/src/server/eula.txt:ro
      - ./configs/hubserver/bukkit.yml:/usr/src/server/bukkit.yml:ro
      - ./configs/hubserver/spigot.yml:/usr/src/server/spigot.yml:ro
      - ./configs/hubserver/server.properties:/usr/src/server/server.properties:ro
      - world_overworld:/usr/src/server/world
      - world_nether:/usr/src/server/world_nether
      - world_the_end:/usr/src/server/world_the_end
    ports:
      - 25580:25580
