forge_support: false
player_limit: -1
timeout: 30000
log_commands: false
online_mode: false
ip_forward: false
network_compression_threshold: 256
prevent_proxy_connections: false
connection_throttle: 4000
stats: d672cf45-0029-49fe-861d-8ec0b26da417
log_pings: true

groups:
  Walonia:
  - admin

permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload

listeners:
- query_port: 25577
  host: 0.0.0.0:25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  ping_passthrough: false
  bind_local_address: false
  max_players: 1
  tab_size: 60
  default_server: hubserver
  fallback_server: hubserver
  priorities:
  - hubserver

servers:
  hubserver:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 0.0.0.0:25580
    restricted: false
