version: '2'

services:
  ackee:
    container_name: ackee
    depends_on:
    - mongo
    image: electerious/ackee
    restart: unless-stopped
    ports:
    - '3030:3000'
    environment:
    - 'VIRTUAL_PORT=3000'
    - 'WAIT_HOSTS=mongo:27017'
    - 'ACKEE_MONGODB=mongodb://mongo:27017/ackee'
    - 'ACKEE_USERNAME=${ACKEE_USERNAME}'
    - 'ACKEE_PASSWORD=${ACKEE_PASSWORD}'
    - 'VIRTUAL_HOST=${VIRTUAL_HOST}'
    - 'LETSENCRYPT_HOST=${LETSENCRYPT_HOST}'

  mongo:
    container_name: ackee-database
    image: mongo
    restart: unless-stopped
    volumes:
    - '${ACKEE_VOLUMES_DIR}/data:/data/db'
