version: '2'

services:
  webserver:
    container_name: paperless
    image: thepaperlessproject/paperless:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
    - "8000:8000"
    volumes:
    - ${PAPERLESS_VOLUMES_DIR}/data:/usr/src/paperless/data
    - ${PAPERLESS_VOLUMES_DIR}/media:/usr/src/paperless/media
    - ${PAPERLESS_VOLUMES_DIR}/consume:/consume
    env_file: .env
    command: ["gunicorn", "-b", "0.0.0.0:8000"]

  consumer:
    container_name: paperless-consumer
    image: thepaperlessproject/paperless:latest
    restart: unless-stopped
    depends_on:
    - webserver
    volumes:
    - ${PAPERLESS_VOLUMES_DIR}/data:/usr/src/paperless/data
    - ${PAPERLESS_VOLUMES_DIR}/media:/usr/src/paperless/media
    - ${PAPERLESS_VOLUMES_DIR}/consume:/consume
    - ${PAPERLESS_VOLUMES_DIR}/export:/export
    env_file: .env
    command: ["document_consumer"]
