version: '2'

services:
  webserver:
    build: thepaperlessproject/paperless:latest
    restart: unless-stopped
    ports:
    - "8000:8000"
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
    - ${PAPERLESS_VOLUMES_DIR}/data:/usr/src/paperless/data
    - ${PAPERLESS_VOLUMES_DIR}/media:/usr/src/paperless/media
    - ${PAPERLESS_VOLUMES_DIR}/consume:/consume
    env_file: .env
    command: ["gunicorn", "-b", "0.0.0.0:8000"]

  consumer:
    build: thepaperlessproject/paperless:latest
    restart: unless-stopped
    depends_on:
      webserver:
        condition: service_healthy
    volumes:
    - ${PAPERLESS_VOLUMES_DIR}/data:/usr/src/paperless/data
    - ${PAPERLESS_VOLUMES_DIR}/media:/usr/src/paperless/media
    - ${PAPERLESS_VOLUMES_DIR}/consume:/consume
    - ${PAPERLESS_VOLUMES_DIR}/export:/export
    env_file: .env
    command: ["document_consumer"]
