version: "3.2"

networks:
  firefly_db_net:
    driver: bridge

volumes:
  firefly_dbdata: ~
  firefly_export: ~
  firefly_upload: ~

services:
  firefly_db:
    image: postgres:alpine
    container_name: firefly_db
    restart: unless-stopped
    networks:
      - firefly_db_net
    volumes:
      - firefly_dbdata:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=firefly

  firefly_app:
    image: jc5x/firefly-iii
    container_name: firefly_app
    restart: unless-stopped
    depends_on:
      - firefly_db
    networks:
      - firefly_db_net
    volumes:
      - firefly_export:/var/www/firefly-iii/storage/export
      - firefly_upload:/var/www/firefly-iii/storage/upload
    ports:
      - 3010:80
    environment:
      - FF_DB_CONNECTION=pgsql
      - FF_DB_HOST=firefly_db
      - FF_DB_NAME=firefly
      - FF_DB_USER=firefly
      - FF_DB_PASSWORD=firefly
      - FF_APP_KEY=S0m3R@nd0mStr1ngOf32Ch@rsEx@ctly
      - FF_APP_ENV=local
      - TZ=Europe/Amsterdam
      - APP_LOG_LEVEL=debug
